AWSTemplateFormatVersion: '2010-09-09'
Resources:
  HelloWorldFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: HelloWorldFunction
      Runtime: python3.8
      Handler: index.handler
      Code:
        ZipFile: |
          import json
          
          def lambda_handler(event, context):
              return {
                  'statusCode': 200,
                  'body': 'Hello, World!'
              }
