AWSTemplateFormatVersion: '2010-09-09'
Resources:
  HelloWorldFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: HelloWorldFunction
      Runtime: python3.7
      Handler: index.handler
      Code:
        S3Bucket: my-code-bucket
        S3Key: lambda_code.py
